### ISSUE TITLE
Before v1.0 (Roadmap)

### ISSUE THREAD

**Issue by ironspecs** [nymag/amphora#110]
Before v1.0 is released, we should establish the following features' API, so that we don't break the API immediately after "release" and have to become v2 ridiculously fast.

Config
- [x] bootstrap.yml in components should be run in each component after startup.
- [x] bootstrap.yml at root of project should be run after startup automatically.
- [x] all config should be moved into `/sites/<site name>` folders
- [ ] ~~api to generate components with dynamically provided data~~

Search / Index pages
- [ ] ~~paging in the format of `{ next: "<uri>", prev: "<uri>" , results: [...] }`~~

Maintainability
- [ ] ~~`/uris/` should have a human-readable version~~
