### ISSUE TITLE
Near-future Roadmap

### ISSUE THREAD

**Issue by TakenPilot** [nymag/amphora#180]
- [x]  Add web hooks for publishing, and unpublishing
- [x]  Sitemaps from list of `/uris` (assuming less than 50,000 urls)
  - [x] sitemap.txt
  - [x] sitemap.xml
- [ ]  Use node's built-in EventEmitter instead of Eventify
- [ ]  Use standard `morgan` and `response-time` response logging instead of logging ourselves in our own format.  (https://scotch.io/bar-talk/expressjs-4-0-new-features-and-upgrading-from-3-0)
- [ ]  Dynamic addition and removal of sites at run-time from `/sites` endpoint.
- [ ]  Addition and removal of users at run-time from `/users` endpoint.
- [x]  Sites should point to themes instead of sites for styles, assets, typography, etc.
- [ ]  Sites should have roles, and Users can be assigned into those roles.

**Comment by yoshokatana** [comment]
Are those breaking changes though? Or were you using `v2` colloquially?

**Comment by TakenPilot** [comment]
I should have just called it roadmap.  : )

**Comment by yoshokatana** [comment]
i fix for u :smile:

**Comment by TakenPilot** [comment]
You are awesome sir!

**Comment by jonwinton** [comment]
Closing as out of date.
